

export const venues = [
  {
    id: 1,
    name: 'The Grand Meadow',
    type: 'Farmhouse',
    location: 'Sunnyvale, CA',
    capacity: 2000000,
    price: 1500,
    offerPrice: 1200,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    images: [
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse field',
      },
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse interior',
      },
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse garden',
      },
    ],
    description:
      'A beautiful farmhouse set in acres of lush green meadows, perfect for weddings and corporate retreats. The Grand Meadow offers a serene escape from the city with modern amenities and breathtaking views.',
    amenities: [
      { name: 'Free Wi-Fi' },
      { name: 'On-site Parking' },
      { name: 'Catering Available' },
      { name: 'Outdoor Space' },
    ],
    owner: {
      name: 'Jane Doe',
      email: 'jane.doe@grandmeadow.com',
      phone: '+1 (555) 123-4567',
    },
    image: "https://placehold.co/600x400.png",
    hint: "farmhouse field",
  },
  {
    id: 2,
    name: 'Crystal Ballroom',
    type: 'Function Hall',
    location: 'Metropolis, NY',
    capacity: 3000000,
    price: 2500,
    offerPrice: null,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: "ballroom wedding"},
        { src: "https://placehold.co/1200x800.png", hint: "ballroom interior"},
        { src: "https://placehold.co/1200x800.png", hint: "ballroom chandeliers"},
    ],
    description: "A stunning ballroom with crystal chandeliers and a grand staircase, ideal for lavish weddings and formal events.",
    amenities: [
      { name: 'Valet Parking' },
      { name: 'In-house Catering' },
      { name: 'Bridal Suite' },
      { name: 'Sound System' },
    ],
    owner: {
        name: "John Smith",
        email: "john.smith@crystalballroom.com",
        phone: "+1 (555) 987-6543",
    },
    image: "https://placehold.co/600x400.png",
    hint: "ballroom wedding",
  },
  {
    id: 3,
    name: 'Oakwood Manor',
    type: 'Farmhouse',
    location: 'Greenwich, CT',
    capacity: 1500000,
    price: 3000,
    offerPrice: 2800,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'manor exterior',
  },
  {
    id: 4,
    name: 'The City Loft',
    type: 'Function Hall',
    location: 'Downtown, LA',
    capacity: 100,
    price: 1800,
    offerPrice: null,
    status: 'Pending', // Changed to Pending
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'loft interior',
  },
  {
    id: 5,
    name: 'Lakeside Retreat',
    type: 'Farmhouse',
    location: 'Lake Tahoe, NV',
    capacity: 80,
    price: 2200,
    offerPrice: null,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'lake house',
  },
  {
    id: 6,
    name: 'Starlight Pavilion',
    type: 'Function Hall',
    location: 'Star City, TX',
    capacity: 5000000,
    price: 4000,
    offerPrice: 3500,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'pavilion night',
  },
    {
    id: 7,
    name: 'My New Hall',
    type: 'Function Hall',
    location: 'City Center',
    status: 'Pending', // Changed to Pending
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern hall',
    price: 1000,
    offerPrice: null,
  },
  {
    id: 8,
    name: 'Rejected Venue',
    type: 'Other',
    location: 'Nowhere',
    status: 'Rejected',
    bookingOptions: 'N/A',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'empty room',
    price: 500,
    offerPrice: null,
  },
  {
    id: 9,
    name: 'The Royal Banquet',
    type: 'Banquet Hall',
    location: 'King\'s Landing, WE',
    capacity: 500,
    price: 4500,
    offerPrice: null,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: "royal banquet"},
        { src: "https://placehold.co/1200x800.png", hint: "banquet hall interior"},
        { src: "https://placehold.co/1200x800.png", hint: "banquet hall dining"},
    ],
    description: "An exquisite banquet hall designed for royal gatherings and grand celebrations. Features opulent decor and world-class service.",
    amenities: [
      { name: 'Valet Parking' },
      { name: 'In-house Catering' },
      { name: 'Sound System' },
      { name: 'Free Wi-Fi' },
    ],
    owner: {
        name: "Cersei Lannister",
        email: "cersei@casterlyrock.com",
        phone: "+1 (555) 555-5555",
    },
    image: "https://placehold.co/600x400.png",
    hint: "royal banquet",
  }
];

export const bookings = [
  {
    id: 'booking-1',
    venueId: 1,
    venueName: 'The Grand Meadow',
    customerName: 'Alice Johnson',
    date: '2024-09-15T00:00:00.000Z',
    guests: 150,
    status: 'Approved',
  },
  {
    id: 'booking-2',
    venueId: 2,
    venueName: 'Crystal Ballroom',
    customerName: 'Bob Williams',
    date: '2024-10-20T00:00:00.000Z',
    guests: 250,
    status: 'Approved',
  },
  {
    id: 'booking-3',
    venueId: 1,
    venueName: 'The Grand Meadow',
    customerName: 'Charlie Brown',
    date: '2024-11-01T00:00:00.000Z',
    guests: 100,
    status: 'Pending',
  },
  {
    id: 'booking-4',
    venueId: 4,
    venueName: 'The City Loft',
    customerName: 'Diana Prince',
    date: '2024-11-12T00:00:00.000Z',
    guests: 80,
    status: 'Pending',
  },
  {
    id: 'booking-5',
    venueId: 6,
    venueName: 'Starlight Pavilion',
    customerName: 'Ethan Hunt',
    date: '2024-12-05T00:00:00.000Z',
    guests: 400,
    status: 'Rejected',
  },
];

export const monthlyBookingsData = [
  { month: "Jan", bookings: 4 },
  { month: "Feb", bookings: 3 },
  { month: "Mar", bookings: 5 },
  { month: "Apr", bookings: 7 },
  { month: "May", bookings: 6 },
  { month: "Jun", bookings: 8 },
];
