

export const availableAmenities = [
  { id: 'wifi', name: 'Wi-Fi' },
  { id: 'parking', name: 'Parking' },
  { id: 'catering', name: 'Catering' },
  { id: 'ac', name: 'Air Conditioning' },
  { id: 'refrigerator', name: 'Refrigerator' },
  { id: 'tv', name: 'TV' },
  { id: 'bridal-suite', name: 'Bridal Suite' },
  { id: 'sound-system', name: 'Sound System' },
  { id: 'valet-parking', name: 'Valet Parking' },
  { id: 'in-house-decor', name: 'In-house Decor' },
  { id: 'lift', name: 'Lift/Elevator' },
  { id: 'dressing-room', name: 'Dressing Room' },
];

export const menuOptions = [
    { id: 'veg', name: 'Veg' },
    { id: 'non-veg', name: 'Non-Veg' },
    { id: 'beef', name: 'Beef' },
];


export const venues = [
  {
    id: 1,
    name: 'The Grand Meadow',
    type: 'Farmhouse',
    location: 'Sunnyvale, CA',
    capacity: 200,
    price12hr: 1200,
    price24hr: 2000,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
    images: [
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse field',
      },
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse interior',
      },
      {
        src: 'https://placehold.co/1200x800.png',
        hint: 'farmhouse garden',
      },
    ],
    description:
      'A beautiful farmhouse set in acres of lush green meadows, perfect for weddings and corporate retreats. The Grand Meadow offers a serene escape from the city with modern amenities and breathtaking views.',
    amenities: ['wifi', 'parking', 'catering', 'ac', 'lift', 'dressing-room'],
    menuOptions: ['veg', 'non-veg'],
    owner: {
      name: 'Jane Doe',
      email: 'jane.doe@grandmeadow.com',
      phone: '+1 (555) 123-4567',
    },
    image: "https://placehold.co/600x400.png",
    hint: "farmhouse field",
  },
  {
    id: 2,
    name: 'Crystal Ballroom',
    type: 'Function Hall',
    location: 'Metropolis, NY',
    capacity: 300,
    priceDay: 2500,
    priceNight: 3500,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: "ballroom wedding"},
        { src: "https://placehold.co/1200x800.png", hint: "ballroom interior"},
        { src: "https://placehold.co/1200x800.png", hint: "ballroom chandeliers"},
    ],
    description: "A stunning ballroom with crystal chandeliers and a grand staircase, ideal for lavish weddings and formal events.",
    amenities: ['valet-parking', 'in-house-decor', 'bridal-suite', 'sound-system', 'lift'],
    menuOptions: ['veg', 'non-veg', 'beef'],
    owner: {
        name: "John Smith",
        email: "john.smith@crystalballroom.com",
        phone: "+1 (555) 987-6543",
    },
    image: "https://placehold.co/600x400.png",
    hint: "ballroom wedding",
  },
  {
    id: 3,
    name: 'Oakwood Manor',
    type: 'Farmhouse',
    location: 'Greenwich, CT',
    capacity: 150,
    price12hr: 2800,
    price24hr: 4500,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'manor exterior',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'manor exterior'},
        { src: "https://placehold.co/1200x800.png", hint: 'manor garden'},
        { src: "https://placehold.co/1200x800.png", hint: 'manor interior'},
    ],
    amenities: ['wifi', 'parking', 'ac', 'tv'],
    menuOptions: ['veg'],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'An elegant manor surrounded by ancient oak trees.'
  },
  {
    id: 4,
    name: 'The City Loft',
    type: 'Function Hall',
    location: 'Downtown, LA',
    capacity: 100,
    priceDay: 1800,
    priceNight: 2200,
    status: 'Pending', 
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'loft interior',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'loft interior'},
        { src: "https://placehold.co/1200x800.png", hint: 'loft rooftop'},
        { src: "https://placehold.co/1200x800.png", hint: 'loft bar'},
    ],
    amenities: ['wifi', 'ac', 'sound-system'],
    menuOptions: ['non-veg', 'beef'],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'A modern and chic loft space for intimate events.'
  },
  {
    id: 5,
    name: 'Lakeside Retreat',
    type: 'Farmhouse',
    location: 'Lake Tahoe, NV',
    capacity: 80,
    price12hr: 2200,
    price24hr: 3800,
    status: 'Published',
    bookingOptions: '12/24 Hour Slots',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'lake house',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'lake house'},
        { src: "https://placehold.co/1200x800.png", hint: 'lake view'},
        { src: "https://placehold.co/1200x800.png", hint: 'house interior'},
    ],
    amenities: ['wifi', 'parking', 'refrigerator'],
    menuOptions: ['veg', 'non-veg'],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'A cozy retreat with stunning views of the lake.'
  },
  {
    id: 6,
    name: 'Starlight Pavilion',
    type: 'Function Hall',
    location: 'Star City, TX',
    capacity: 500,
    priceDay: 3500,
    priceNight: 4500,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'pavilion night',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'pavilion night'},
        { src: "https://placehold.co/1200x800.png", hint: 'pavilion setup'},
        { src: "https://placehold.co/1200x800.png", hint: 'pavilion lights'},
    ],
    amenities: ['parking', 'sound-system', 'in-house-decor'],
    menuOptions: ['veg', 'non-veg'],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'A grand pavilion perfect for large-scale events under the stars.'
  },
    {
    id: 7,
    name: 'My New Hall',
    type: 'Function Hall',
    location: 'City Center',
    status: 'Pending',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern hall',
    priceDay: 1000,
    priceNight: 1500,
    capacity: 100,
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'modern hall'},
        { src: "https://placehold.co/1200x800.png", hint: 'hall stage'},
        { src: "https://placehold.co/1200x800.png", hint: 'hall seating'},
    ],
    amenities: [],
    menuOptions: [],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'A newly renovated hall in the heart of the city.'
  },
  {
    id: 8,
    name: 'Rejected Venue',
    type: 'Other',
    location: 'Nowhere',
    status: 'Rejected',
    bookingOptions: 'N/A',
    videoUrl: '',
    image: 'https://placehold.co/600x400.png',
    hint: 'empty room',
    priceDay: 500,
    priceNight: 500,
    capacity: 10,
    images: [
        { src: "https://placehold.co/1200x800.png", hint: 'empty room'},
        { src: "https://placehold.co/1200x800.png", hint: 'blank space'},
    ],
    amenities: [],
    menuOptions: [],
    owner: { name: 'N/A', email: '', phone: '' },
    description: 'This venue submission was not approved.'
  },
  {
    id: 9,
    name: 'The Royal Banquet',
    type: 'Banquet Hall',
    location: 'King\'s Landing, WE',
    capacity: 500,
    priceDay: 4500,
    priceNight: 6000,
    status: 'Published',
    bookingOptions: 'Day/Night Events',
    videoUrl: '',
    images: [
        { src: "https://placehold.co/1200x800.png", hint: "royal banquet"},
        { src: "https://placehold.co/1200x800.png", hint: "banquet hall interior"},
        { src: "https://placehold.co/1200x800.png", hint: "banquet hall dining"},
    ],
    description: "An exquisite banquet hall designed for royal gatherings and grand celebrations. Features opulent decor and world-class service.",
    amenities: ['valet-parking', 'in-house-decor', 'sound-system', 'wifi'],
    menuOptions: ['veg', 'non-veg', 'beef'],
    owner: {
        name: "Cersei Lannister",
        email: "cersei@casterlyrock.com",
        phone: "+1 (555) 555-5555",
    },
    image: "https://placehold.co/600x400.png",
    hint: "royal banquet",
  }
];

export const bookings = [
  {
    id: 'booking-1',
    venueId: 1,
    venueName: 'The Grand Meadow',
    customerName: 'Alice Johnson',
    date: '2024-09-15T00:00:00.000Z',
    guests: 150,
    status: 'Approved',
  },
  {
    id: 'booking-2',
    venueId: 2,
    venueName: 'Crystal Ballroom',
    customerName: 'Bob Williams',
    date: '2024-10-20T00:00:00.000Z',
    guests: 250,
    status: 'Approved',
  },
  {
    id: 'booking-3',
    venueId: 1,
    venueName: 'The Grand Meadow',
    customerName: 'Charlie Brown',
    date: '2024-11-01T00:00:00.000Z',
    guests: 100,
    status: 'Pending',
  },
  {
    id: 'booking-4',
    venueId: 4,
    venueName: 'The City Loft',
    customerName: 'Diana Prince',
    date: '2024-11-12T00:00:00.000Z',
    guests: 80,
    status: 'Pending',
  },
  {
    id: 'booking-5',
    venueId: 6,
    venueName: 'Starlight Pavilion',
    customerName: 'Ethan Hunt',
    date: '2024-12-05T00:00:00.000Z',
    guests: 400,
    status: 'Rejected',
  },
];

export const monthlyBookingsData = [
  { month: "Jan", bookings: 4 },
  { month: "Feb", bookings: 3 },
  { month: "Mar", bookings: 5 },
  { month: "Apr", bookings: 7 },
  { month: "May", bookings: 6 },
  { month: "Jun", bookings: 8 },
];
